/* 
 * File:   main.cpp
 * Author: Abel S. Esqueda
 * Created on June 20, 2016, 6:51 PM
 * Purpose: Template
 */

//System Libraries
#include <iostream>  //Input/Output Library
using namespace std; //Namespace of the System Libraries

//User Libraries

//Global Constants

//Function Prototypes

//Execution Begins Here!
int main(int argc, char** argv) {
    //Declare Variables
    float totsale;       //Total Sales for the company
    float ECDiv;         //The sales generated by the East Coast Division

    //Input Data
    
    //Process Data
    totsale=8.6e6;       //The total sales were 8.6 million
    ECDiv=totsale*.58;   //East coast division made 58 percent of that
    
    //Output the processed Data
    cout<<"The total sales for Company X is 8.6 Million."<<endl;
    cout<<"The East Coast Division alone generated 58 percent"
            <<"of the Companies total sales."<<endl;
    cout <<"So the East Coast Division generated $"<<ECDiv<<
            " or 4.988 Million dollars."<<endl;
         
    
    //Exit Stage Right!
    return 0;
}

