/* 
 * File:   main.cpp
 * Author: Abel S. Esqueda
 * Created on June 20, 2016, 6:51 PM
 * Purpose: Template
 */

//System Libraries
#include <iostream>  //Input/Output Library
using namespace std; //Namespace of the System Libraries

//User Libraries

//Global Constants

//Function Prototypes

//Execution Begins Here!
int main(int argc, char** argv) {
    //Declare Variables
    float Totsale;
    float ECDiv;

    //Input Data
    
    //Process Data
    Totsale=8.6e6;       //Total sales for the company
    ECDiv=Totsale*.58;   //The Amount generated by the East Coast Division
    
    //Output the processed Data
    cout<<"The Total Sales for Company x is 8.6 Million dollars"<<endl;
    cout<<"The East Coast Sales Division generates "
            <<"58 percent of the companies total sales"<<endl;
    cout<<"The East Coast Division generates $"<<ECDiv
    <<" or 4.988 Million dollars."<<endl;
    
    //Exit Stage Right!
    return 0;
}

